### ISSUE TITLE
Production ready

### ISSUE THREAD

**Issue by andreialecu** [OpenDataFormats/worldcities#1]
Hey! Just found this and it looks very interesting. I was wondering why this warning exists:

> BETA Absolutely not production ready! Do not even think about using this version!

If you're looking for help, what would be required exactly?

**Comment by davidarvan** [comment]
Hey thanks! I made this library because I've worked on multiple projects that use location data, but store it, correctly, as GPS coordinates. When that data is presented in the UI though, it's helpful to also have the name of the closest city, which is much more legible than a pair of floating point numbers.

There may no longer be a reason it can't be used, there is 100% code coverage
https://coveralls.io/github/OpenDataFormats/worldcities?branch=master

I just wanted to do a focused full audit before telling anyone to use it. Absolutely use it if you think it will be useful, and if you find any issues definitely let me know.

**Comment by andreialecu** [comment]
That's why I was asking, I was just testing it out and it seems to work pretty nicely. That warning was pretty scary, didn't know what to expect. :)

**Comment by davidarvan** [comment]
Haha, I could probably tone down the language.

**Comment by andreialecu** [comment]
I did notice an issue though, probably with the data. I'll open a separate issue for it.
