### ISSUE TITLE
getNearestLargeCity returns district names instead of city names in some cases

### ISSUE THREAD

**Issue by andreialecu** [OpenDataFormats/worldcities#2]
```ts
    console.log(worldcities.getNearestLargeCity(44.429, 26.148));
```

This prints:

```
City {
  latitude: 44.4234,
  longitude: 26.16874,
  name: 'Sector 3',
  population: 385439,
  timezone: 'Europe/Bucharest',
  country: Country {
    areaSquareMeters: 237500,
    callingCode: '40',
    capital: 'Bucharest',
    continent: 'EU',
    countryCode: 'RO',
    countryCode3: 'ROU',
    currencyCode: 'RON',
    currencyName: 'Leu',
    languages: [ 'ro', 'hu', 'rom' ],
    name: 'Romania',
    neighbors: [ 'MD', 'HU', 'UA', 'BG', 'RS' ],
    population: 19473936,
    postalCodeRegExp: '^(\\d{6})$',
    tld: '.ro',
    wikipedia: 'Romania',
    geoJSON: undefined,
    flagSVG: undefined
  }
}
```

However, "Sector 3" is not a city but a district within Bucharest (a division of the city - there are Sectors between 1-6). 

The granularity is good, it's nice that it goes that deep within the city. But I wonder if it's possible to also return that it's part of Bucharest somehow.

**Comment by davidarvan** [comment]
Oh wow, interesting find, thanks! That is how it is labelled in the underlying datasets from GeoNames.

Given there may be more cases like this, I think it makes sense to add an additional step to the build process, right now it is:
Pull Data -> Parse -> Convert -> Export

I will add a step so that it's like this:
Pull Data -> Parse -> Convert -> Apply Corrections -> Export

Would it work to change these labels so the city name is "Bucharest", and add an additional, optional key like
"district": "Sector 3"
?

**Comment by andreialecu** [comment]
Well, I noticed that the `population` is also that of `Sector 3` (as Bucharest has 2 million+). 

So maybe something like this would be better:

```
name: "Bucharest",
population: 12345678,
district: {
  name: "Sector 3",
  population: 385439
}
```

**Comment by davidarvan** [comment]
Good call, I'll whip up a change to handle these cases.
